software_groups: &software
  - "base_focal"

packages:
  branch_codenames:
    master: focal-unstable
    production: focal-stable

jobs:
  slackcat:
    builder: "make"
    base: "quay.io/madebymany/build-bases:focal"
    software_groups: *software
    build_depends:
      - "golang"
    promote_through:
      - unstable
      - stable
    packages:
      - name: slackcat
        repos:
          - mxm-public
        target: install
